### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by photry** [SniperGER/LockWatch2#1]
Conflict package and subprocess error (1) - ipadOS ipad pro 13.2.3

**Comment by SniperGER** [comment]
Sorry for the late response, I don't watch my GitHub issues automatically for some reason.

This build (and probably following builds) are marked as incompatible with iPads because these devices are missing files that are only found inside iPhone IPSWs, which you'll need to copy over manually at this point. I recommend downloading the iPhone X IPSW from ipsw.me or the same iOS version as your iPad (13.2.3 in this case).

These are the files you'll need to copy:
```
/System/Library/PrivateFrameworks/NanoTimeKitCompanion/*
/System/Library/PrivateFrameworks/NanoUniverse.framework/*
```

I hope I can do this automatically at some point, but I have absolutely no idea how to do it.
Also, this will _NOT_ make this build magically installable. This is just to prepare for future builds that aren't marked as incompatible with iPad.

I'm going to close this issue since this behavior is intentional at this point. If you have any questions or concerns, feel free to comment.
