### ISSUE TITLE
Moves/ interference with Photon

### ISSUE THREAD

**Issue by ArmasF31** [SniperGER/LockWatch2#6]
The position changes, I have no idea why this is happening :)
Anyway, I love your work <3 I was searching for this so long...
I attached you two photos so you can see what I mean
![74694356-5351-4B4F-B096-9F624642FB37](https://user-images.githubusercontent.com/66262484/83419977-36017880-a426-11ea-951c-639b9d6cb097.png)
![905115F5-6671-4512-912B-05425F3603B6](https://user-images.githubusercontent.com/66262484/83419989-3994ff80-a426-11ea-9afe-f3ac849efc22.png)

I hope I could help you find a bug.

**Comment by SniperGER** [comment]
I was just messing around with Photon, and I've come to the conclusion that this is an issue with Photon rather than LockWatch. All that LockWatch is replacing the stock iOS clock, and Photon isn't handling the presence of LockWatch correctly.

I'll contact the developer to see what we can do about it.

**Comment by SniperGER** [comment]
Had a great conversation with the developer of Photon. Turns out this actually is a LockWatch issue. It's fixed internally already and will be pushed to public soon™.

**Comment by SniperGER** [comment]
Update is now released on https://repo.festival.tf!
